[build]
builder = "DOCKERFILE"
dockerfilePath = "backend-lms/Dockerfile"

[deploy]
startCommand = "cd backend-lms && php artisan migrate:fresh --seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
