[build]
builder = "DOCKERFILE"
dockerfilePath = "backend-lms/Dockerfile"

[deploy]
startCommand = "php artisan key:generate --force && php artisan migrate:fresh --seed --force && apache2-foreground"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
