[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend-lms && php artisan key:generate --force && php artisan migrate:fresh --seed --force && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
